apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira-software.fullname" . }}
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }} #consider changing default in values to LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http 
  selector:
    {{- include "jira-software.selectorLabels" . | nindent 4 }}
