apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jira-software.fullname" . }}
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "jira-software.fullname" . }}
  selector:
    matchLabels:
      {{- include "jira-software.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jira-software.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jira-software.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ATL_JDBC_URL
              value: "{{ .Values.db.url }}"
            - name: ATL_DB_DRIVER
              value: "{{ .Values.db.driver }}"
            - name: ATL_DB_TYPE
              value: "{{ .Values.db.type }}"
            - name: ATL_JDBC_USER
              value: "{{ .Values.db.user }}"
            {{if .Values.db.schema }}
            - name: ATL_DB_SCHEMA_NAME
              value: "{{ .Values.db.schema }}"
            {{end}}
            - name: ATL_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jira-software.secretName" . }}
                  key: jira-software-password
            - name: JIRASW_DB
              value: "{{ .Values.db.name }}"
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              value: "{{ .Values.jvmargs }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /var/atlassian/application-data/jira
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{if .Values.storage.storageClass}}storageClassName: {{ .Values.storage.storageClass}}{{ end }}
      resources:
        requests:
          storage: {{ .Values.storage.storageSize | quote }}
