{{- if (.Values.db.useExternalSecret) }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-wikijs-token
spec: 
{{ with .Values.db.externalSecretData.providerPayload -}}
{{ toYaml . | indent 2 -}}
{{- end }}
{{- end }}