{{- if (.Values.db.useExternalSecret) }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-wikijs-token
spec:
  {{- with .Values.db.externalSecretData.providerPayload -}}
  provider: 
{{ toYaml . | indent 4 -}}
  {{- end }}
{{- end }}