{{- if (.Values.db.useExternalSecret) -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-wikijs-token
spec:
  provider:
    #note - should probably put some further validation here... 
    {{-  toYaml .Values.db.externalSecretData.providerPayload | indent 4 }}
{{- end }}