{{- if (.Values.db.useExternalSecret) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: doppler-wikijs
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-wikijs-token
  target:
    name: wikijs
  data:
    - secretKey: db-password
      remoteRef:
        {{- if not (empty .Values.db.externalSecretData.passwordRef) }}
        key: {{ .Values.db.externalSecretData.passwordRef }}
        {{- else }}
        key: DB_PASS #default value
        {{- end }}
    - secretKey: db-user
      remoteRef:
        {{- if not (empty .Values.db.externalSecretData.userRef) }}
        key: {{ .Values.db.externalSecretData.userRef }}
        {{- else }}
        key: DB_USER #default value
        {{- end }}
{{- end }}