{{- if .Values.httproute.enabled -}}
{{- $fullName := include "wikijs.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:     
    {{- include "wikijs.labels" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
   {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.httproute.gateway.name }}
    namespace: {{ .Values.httproute.gateway.namespace }}
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ $fullName }}
      port: {{ $svcPort }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}