{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wikijs.fullname" . }}
  labels:
    app: "{{ template "wikijs.name" . }}"
    chart: "{{ template "wikijs.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not (empty .Values.db.user) }}
  db-user: "{{ .Values.db.user | b64enc }}"
  {{- else }}
  db-user: {{ required "A Database User is required!" .Values.db.user }}
  {{- end }}
  {{- if not (empty .Values.db.password) }}
  db-password: "{{ .Values.db.password | b64enc }}"
  {{- else }}
  db-password: {{ required "A Database Password is required!" .Values.db.password }}
  {{- end }}
{{- end }}