{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "confluence-software.fullname" . }}
  labels:
    app: "{{ template "confluence-software.name" . }}"
    chart: "{{ template "confluence-software.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not (empty .Values.db.user) }}
  {{- if not (empty .Values.db.password) }}
  confluence-software-password: "{{ .Values.db.password | b64enc }}"
  {{- else if (not .Values.db.forcePassword) }}
  confluence-software-password: "{{ randAlphaNum 10 | b64enc }}"
  {{- else }}
  confluence-software-password: {{ required "A confluence-software Database Password is required!" .Values.db.password }}
  {{- end }}
  {{- end }}
{{- end }}