apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-headless
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis-master
    - port: {{ .Values.slaveService.port }}
      targetPort: redis-slave
      protocol: TCP
      name: redis-slave  
    - port: {{ add .Values.service.port 10000}}
      targetPort: redis-cluster
      protocol: TCP
      name: redis-cluster-master
    - port: {{ add .Values.slaveService.port 10000}}
      targetPort: redis-cluster
      protocol: TCP
      name: redis-cluster-slave  
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
