{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sparkserver.fullname" . }}
  labels:
    app: "{{ template "sparkserver.name" . }}"
    chart: "{{ template "sparkserver.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not (empty .Values.ConnectionString) }}
  connection-string: "{{ .Values.ConnectionString | b64enc }}"
  {{- else }}
  connection-string: {{ required "A valid ConnectionString is required!" .Values.ConnectionString }}
  {{- end }}
  {{- if not (empty .Values.certificate)}}
  certificate: "{{ .Files.Get .Values.certificate | b64enc }}"
  {{- else }}
  certificate: {{ required "A certificate file is required!" .Values.certificate }}
  {{- end }}
  {{- if not (empty .Values.certificatepass) }}
  certificate-pass: "{{ .Values.certificatepass | b64enc }}"
  {{- else }}
  certificate-pass: {{ required "A certificate password is required!" .Values.certificatepass }}
  {{- end}}
{{- end }}