{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app: "{{ template "postgres.name" . }}"
    chart: "{{ template "postgres.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not (empty .Values.db.user) }}
  {{- if not (empty .Values.db.password) }}
  postgres-password: "{{ .Values.db.password | b64enc }}"
  {{- else if (not .Values.db.forcePassword) }}
  postgres-password: "{{ randAlphaNum 10 | b64enc }}"
  {{- else }}
  postgres-password: {{ required "A postgres Database Password is required!" .Values.db.password }}
  {{- end }}
  {{- end }}
{{- end }}