apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }} #consider changing default in values to LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http # should not be http, instead use port number
      protocol: TCP
      name: http #should not be http
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
